# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="musashi"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(history git rbenv git rails bundler)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=pl_PL.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
#
function git_commit_all_with_no_quotas {
  git commit -a -m "$*"
  git status
}
alias gca='git_commit_all_with_no_quotas'

alias glg='git lg'
function gitprompt {
  vcprompt --format "(%s:%b%m%a%u)"
}
alias buc='bundle check'
# export http_proxy=http://localhost:5865
# export https_proxy=http://localhost:5865
# export EDITOR=/usr/bin/gvim
# export NLS_LANG=American_America.UTF8
# alias g='gvim --remote-silent -geometry 160x60'
# alias vi='g'
# alias mml='ssh acsgw'
#
# alias t='tmux -2'
#
# alias ys='yard server --reload'
#
# alias mms='be middleman server'
# alias mmb='be middleman build'
#
# alias be='bundle exec'
# alias bi='bundle install'
# alias buc='bundle check'
# alias ber='be rspec'
# alias beg='be guard'
# alias bec='be rails c'
# alias best='be rails s -e staging'
# alias bep='be rails s -e production'
# alias berk='be rake'
# alias bem='be middleman'
#
# alias gst='git status'
# alias gid='git add'
# alias grm='git rm'
# alias gdf='git diff'
# alias gad='git add .;git status'
# alias gitp='git push;git status'
# alias gca='git_commit_all_with_no_quotas'
# function start_rails {
# if [ -f ./script/server ]; then
#   bundle exec script/server
# else
#   be rails s -b 127.0.0.1
# fi
# }
# alias bes='start_rails'
# function git_commit_all_with_no_quotas {
#   git commit -a -m "$*"
#   git status
# }
# alias glg='git lg'
# function gitprompt {
#   vcprompt --format "(%s:%b%m%a%u)"
# }
#
# alias rsg='ssh jelcz'
# alias rserver='ruby -run -ehttpd . -p3000'
